### ISSUE TITLE
-s option causes strange strings appear in output

### ISSUE THREAD

**Issue by pavelrad** [jvz/psgrep#4]
> $ psgrep -s test
> ps: euser: keyword not found
> ps: euser: keyword not found

These two strings appear in output every time, even if something is found.
I'm running psgrep 1.0.7 on OS X 10.10.5.

**Comment by jvz** [comment]
Huh, these might be Linux-specific options.

**Comment by pavelrad** [comment]
Yes, there is no `euser` keyword in Apple's implementation of [ps](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/ps.1.html).

**Comment by jvz** [comment]
Alright, I see that `-o user` should work on BSD/OSX, but I need to test this in Linux as well.

**Comment by jvz** [comment]
Thanks for the bug report! I'll release 1.0.8 tonight.

**Comment by pavelrad** [comment]
Thank you for the fix! :)
